services:
  nginx:
    image: "jc21/nginx-proxy-manager:latest"
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - ./data:/data:Z
      - letsencrypt:/etc/letsencrypt:Z

  db:
    image: postgres
    container_name: database
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgresql:/var/lib/postgresql/data:Z

  pgadmin4:
    image: elestio/pgadmin
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${ADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${ADMIN_PASSWORD}
      PGADMIN_LISTEN_PORT: 8080
    ports:
      - "8080:8080"
    volumes:
      - ./servers.json:/pgadmin4/servers.json:Z

  backend:
    build: ./backend
    container_name: backend
    restart: always
    depends_on:
      - db
    ports:
      - "8000:8000"

  dashboard:
    build: ./dashboard
    container_name: dashboard
    restart: always
    depends_on:
      - db
      - backend
    ports:
      - "5173:5173"

  frontend:
    build: ./frontend
    container_name: frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:3000"

volumes:
  postgresql:
  letsencrypt:
